// Pages légales (modèles à relire par un juriste). [[…]] = information à compléter par KPW.
import { MARQUE } from './config.js';

const contact = () => MARQUE.contact || '[[adresse e-mail de contact]]';

export function pageLegale(page, langue) {
  const en = langue === 'en';
  const P = {
    mentions: en ? {
      titre: 'Legal notice',
      sections: [
        ['Publisher', [`RealRoom is published by KPW, [[first and last name]], sole trader (micro-entreprise), [[postal address]], SIRET [[number]]. Contact: ${contact()}.`, 'Publication director: [[first and last name]].']],
        ['Hosting', ['Vercel Inc., 440 N Barranca Ave #4133, Covina, CA 91723, USA (vercel.com). Database: Neon (Postgres). Files: Vercel Blob.']],
        ['Furniture and product photos', ['The furniture offered in RealRoom comes from the Maison Corleone catalogue (maisoncorleone.com). Product names and photos belong to Maison Corleone and are used with its agreement [[to be confirmed in writing]]. Furniture is sold by Maison Corleone, not by KPW.']],
        ['Intellectual property', ['The RealRoom service (software, interface, texts, brand) belongs to KPW. Any reproduction without permission is prohibited.']]
      ]
    } : {
      titre: 'Mentions légales',
      sections: [
        ['Éditeur', [`RealRoom est édité par KPW, [[prénom et nom]], entrepreneur individuel (micro-entreprise), [[adresse postale]], SIRET [[numéro]]. Contact : ${contact()}.`, 'Directeur de la publication : [[prénom et nom]].']],
        ['Hébergement', ['Vercel Inc., 440 N Barranca Ave #4133, Covina, CA 91723, États-Unis (vercel.com). Base de données : Neon (Postgres). Fichiers : Vercel Blob.']],
        ['Meubles et photos des produits', ['Les meubles proposés dans RealRoom viennent du catalogue Maison Corleone (maisoncorleone.com). Les noms et photos des produits appartiennent à Maison Corleone et sont utilisés avec son accord [[à confirmer par écrit]]. Les meubles sont vendus par Maison Corleone, pas par KPW.']],
        ['Propriété intellectuelle', ['Le service RealRoom (logiciel, interface, textes, marque) appartient à KPW. Toute reproduction sans autorisation est interdite.']]
      ]
    },
    cgv: en ? {
      titre: 'Terms of sale',
      sections: [
        ['1. Service', ['RealRoom, published by KPW, turns photos of a room into a 3D model, suggests layouts with real furniture from the Maison Corleone catalogue, and generates AI images (photo renders) and 3D tours, paid with credits.']],
        ['2. Account', ['Sign-in uses a code sent by email. You keep your email address secure and give accurate information.']],
        ['3. Credits and prices', ['Credits are sold in packs; prices are shown including all taxes [[VAT: "VAT not applicable, art. 293 B of the French tax code" if the franchise applies]]. A photo render costs 1 credit, a 3D tour 5 credits; photos, 3D model and layouts are free. Credits do not expire. A generation that fails is refunded automatically in credits. Free credits offered at sign-up cannot be exchanged for money.']],
        ['4. Payment', ['Payment is made by card through Stripe. KPW never sees your card details. A receipt is emailed by Stripe.']],
        ['5. Right of withdrawal', ['Credits are digital content supplied immediately. Before paying, you ask for immediate use and acknowledge that you lose your right of withdrawal for the credits you use. Unused credits of a pack can be refunded within 14 days of purchase on request to ' + contact() + ' [[policy to be validated]].']],
        ['6. AI-generated results', ['Renders and 3D tours are generated by artificial intelligence from your photos, the 3D model and product photos. They can contain errors or inconsistencies (proportions, colours, details) and are not contractual. The 3D model is an approximation, not a survey: check the dimensions of your room and of each piece before buying.']],
        ['7. Buying furniture', ['Furniture is sold by Maison Corleone on maisoncorleone.com under its own terms. KPW is not the seller and is not a party to that sale.']],
        ['8. Your photos', ['You confirm that you have the right to use the photos you upload and avoid photographing people. They are only used to provide the service (see the privacy policy).']],
        ['9. Liability and availability', ['KPW does its best to keep the service available but cannot guarantee uninterrupted service. KPW is not liable for decisions made on the basis of AI-generated images.']],
        ['10. Mediation and law', ['Consumer mediator: [[name and website of the mediator]]. These terms are governed by French law.']]
      ]
    } : {
      titre: 'Conditions générales de vente',
      sections: [
        ['1. Service', ['RealRoom, édité par KPW, transforme les photos d’une pièce en maquette 3D, propose des aménagements avec de vrais meubles du catalogue Maison Corleone, et génère des images par IA (rendus photo) et des visites 3D, payées en crédits.']],
        ['2. Compte', ['La connexion se fait par un code envoyé par e-mail. Vous gardez votre adresse e-mail sécurisée et donnez des informations exactes.']],
        ['3. Crédits et prix', ['Les crédits sont vendus par packs, aux prix affichés toutes taxes comprises [[TVA : « TVA non applicable, art. 293 B du CGI » si la franchise s’applique]]. Un rendu photo coûte 1 crédit, une visite 3D 5 crédits ; photos, maquette 3D et aménagements sont gratuits. Les crédits n’expirent pas. Une génération qui échoue est recréditée automatiquement. Les crédits offerts à l’inscription ne sont pas échangeables contre de l’argent.']],
        ['4. Paiement', ['Le paiement se fait par carte via Stripe. KPW n’a jamais accès à vos données bancaires. Un reçu est envoyé par Stripe.']],
        ['5. Droit de rétractation', ['Les crédits sont un contenu numérique fourni immédiatement. Avant de payer, vous demandez à pouvoir les utiliser tout de suite et reconnaissez perdre votre droit de rétractation pour les crédits utilisés (article L221-28 du Code de la consommation). Les crédits non utilisés d’un pack peuvent être remboursés dans les 14 jours suivant l’achat, sur demande à ' + contact() + ' [[politique à valider]].']],
        ['6. Résultats générés par IA', ['Les rendus et visites 3D sont générés par intelligence artificielle à partir de vos photos, de la maquette et des photos des produits. Ils peuvent contenir des erreurs ou des incohérences (proportions, couleurs, détails) et ne sont pas contractuels. La maquette est une approximation, pas un relevé : vérifiez les dimensions de votre pièce et de chaque meuble avant d’acheter.']],
        ['7. Achat des meubles', ['Les meubles sont vendus par Maison Corleone sur maisoncorleone.com, selon ses propres conditions. KPW n’est pas le vendeur et n’est pas partie à cette vente.']],
        ['8. Vos photos', ['Vous garantissez avoir le droit d’utiliser les photos que vous envoyez et évitez d’y photographier des personnes. Elles servent uniquement à fournir le service (voir la politique de confidentialité).']],
        ['9. Responsabilité et disponibilité', ['KPW fait de son mieux pour que le service reste disponible sans pouvoir garantir l’absence d’interruption. KPW n’est pas responsable des décisions prises sur la base d’images générées par IA.']],
        ['10. Médiation et droit applicable', ['Médiateur de la consommation : [[nom et site du médiateur]]. Les présentes conditions sont soumises au droit français.']]
      ]
    },
    confidentialite: en ? {
      titre: 'Privacy policy',
      sections: [
        ['Controller', [`KPW, [[postal address]], ${contact()}.`]],
        ['Data we process', ['Your email address; the photos of your rooms, their 3D models and layouts; generated images and 3D tours; your credit history (Stripe handles card payments: we only keep the payment reference and amount); technical logs.']],
        ['Why', ['To provide the service you order (contract), to secure it, and to meet accounting obligations.']],
        ['Processors', ['Vercel (hosting and files), Neon (database), Anthropic (analysis of your photos and layout suggestions with Claude), fal.ai (photo renders), World Labs (3D tours), Stripe (payment), Resend (sign-in emails). Some are located in the United States; transfers rely on the European Commission’s standard contractual clauses. Your photos are not used to train models by KPW [[check each provider’s terms]].']],
        ['How long', ['Account data: until you delete your account. Photos, models and renders: deleted with the room, the project or the account. Sign-in codes: 10 minutes. Accounting records: 10 years. To prevent abuse of the free credits, a non-reversible fingerprint of your email address is kept after the account is deleted; it cannot be used to find your address. Copies kept by the processors for the time of a generation follow their own terms [[check fal.ai and World Labs retention]].']],
        ['Your rights', ['Access, rectification, erasure (the “Delete my account” button removes everything), portability, objection: write to ' + contact() + '. You can lodge a complaint with the CNIL (cnil.fr).']],
        ['Cookies', ['A single session cookie (required to stay signed in) and a language preference. No advertising or tracking cookies.']]
      ]
    } : {
      titre: 'Politique de confidentialité',
      sections: [
        ['Responsable du traitement', [`KPW, [[adresse postale]], ${contact()}.`]],
        ['Données traitées', ['Votre adresse e-mail ; les photos de vos pièces, leurs maquettes et aménagements ; les images et visites 3D générées ; l’historique de vos crédits (les paiements par carte sont traités par Stripe : nous ne gardons que la référence et le montant) ; des journaux techniques.']],
        ['Finalités et bases légales', ['Fournir le service que vous commandez (contrat), le sécuriser, et respecter nos obligations comptables (obligation légale).']],
        ['Sous-traitants', ['Vercel (hébergement et fichiers), Neon (base de données), Anthropic (analyse de vos photos et propositions d’aménagement avec Claude), fal.ai (rendus photo), World Labs (visites 3D), Stripe (paiement), Resend (e-mails de connexion). Certains sont situés aux États-Unis ; les transferts reposent sur les clauses contractuelles types de la Commission européenne. KPW n’utilise pas vos photos pour entraîner des modèles [[vérifier les conditions de chaque prestataire]].']],
        ['Durées de conservation', ['Données du compte : jusqu’à sa suppression. Photos, maquettes et rendus : supprimés avec la pièce, le projet ou le compte. Codes de connexion : 10 minutes. Pièces comptables : 10 ans. Pour éviter les abus des crédits offerts, une empreinte non réversible de votre adresse e-mail est conservée après la suppression du compte ; elle ne permet pas de retrouver l’adresse. Les copies gardées par les sous-traitants le temps d’une génération suivent leurs propres conditions [[vérifier la conservation chez fal.ai et World Labs]].']],
        ['Vos droits', ['Accès, rectification, effacement (le bouton « Supprimer mon compte » efface tout), portabilité, opposition : écrivez à ' + contact() + '. Vous pouvez adresser une réclamation à la CNIL (cnil.fr).']],
        ['Cookies', ['Un seul cookie de session (nécessaire pour rester connecté) et une préférence de langue. Aucun cookie publicitaire ni de mesure d’audience.']]
      ]
    }
  };
  return P[page] || null;
}
