'use client';
import {useEffect,useRef,useState} from 'react';
import {VERSION_SCAN} from '@/lib/scan.js';
import s from './Acquisition.module.css';

export default function PlanTrace({lang='fr',onScan,disabled=false}){
 const fr=lang==='fr',[image,setImage]=useState(null),[taille,setTaille]=useState([1000,700]),[points,setPoints]=useState([]),[repere,setRepere]=useState([]),[longueur,setLongueur]=useState(''),[phase,setPhase]=useState('echelle'),[erreur,setErreur]=useState(''),[pdf,setPdf]=useState(null),[page,setPage]=useState(1),[attente,setAttente]=useState(false),jeton=useRef(0);
 const pdfRef=useRef(null);
 useEffect(()=>()=>{jeton.current++;pdfRef.current?.destroy();},[]);
 async function rendre(doc,n,j){const p=await doc.getPage(n),vp=p.getViewport({scale:1}),v=p.getViewport({scale:Math.min(2,1400/Math.max(vp.width,vp.height))}),c=document.createElement('canvas');c.width=v.width;c.height=v.height;await p.render({canvasContext:c.getContext('2d'),viewport:v}).promise;if(j===jeton.current){setImage(c.toDataURL('image/png'));setTaille([c.width,c.height]);setPage(n);setPoints([]);setRepere([]);setPhase('echelle');}}
 async function ouvrir(f){if(!f)return;const j=++jeton.current;setAttente(true);setErreur('');setImage(null);setPdf(null);setPoints([]);setRepere([]);setPhase('echelle');try{
  if(f.size>15e6)throw Error();
  await pdfRef.current?.destroy();pdfRef.current=null;
  if(/\.pdf$/i.test(f.name)){const lib=await import('pdfjs-dist/legacy/build/pdf.mjs');lib.GlobalWorkerOptions.workerSrc='/pdf/pdf.worker.min.mjs?v=5.4.624-legacy';const doc=await lib.getDocument({data:new Uint8Array(await f.arrayBuffer()),isEvalSupported:false}).promise;if(j!==jeton.current){await doc.destroy();return;}pdfRef.current=doc;setPdf(doc);await rendre(doc,1,j);}
  else {const url=URL.createObjectURL(f);try{const im=new Image();im.src=url;await im.decode();const c=document.createElement('canvas'),k=Math.min(1,1400/Math.max(im.width,im.height));c.width=Math.round(im.width*k);c.height=Math.round(im.height*k);c.getContext('2d').drawImage(im,0,0,c.width,c.height);if(j===jeton.current){setImage(c.toDataURL('image/jpeg',.85));setTaille([c.width,c.height]);}}finally{URL.revokeObjectURL(url);}}
 }catch(e){console.warn('Ouverture du plan',e?.name,e?.message);if(j===jeton.current)setErreur(fr?'Impossible d’ouvrir ce plan. Choisissez un PDF non protégé ou une image PNG/JPEG de moins de 15 Mo.':'Could not open this plan. Choose an unprotected PDF or PNG/JPEG below 15 MB.');}finally{if(j===jeton.current)setAttente(false);}}
 const metres=Number(longueur.replace(',','.')),distance=repere.length===2?Math.hypot(repere[1][0]-repere[0][0],repere[1][1]-repere[0][1]):0,echelle=metres/distance;
 function poser(e){if(attente)return;const b=e.currentTarget.getBoundingClientRect(),p=[(e.clientX-b.left)*taille[0]/b.width,(e.clientY-b.top)*taille[1]/b.height];if(phase==='echelle')setRepere(v=>v.length===2?[p]:[...v,p]);else setPoints(v=>v.length<32?[...v,p]:v);}
 function utiliser(){try{onScan({version:VERSION_SCAN,source:'plan-dessine',unit:'m',floorCorners:points.map(([x,z])=>[x*echelle,0,z*echelle]),ceilingHeight:null,openings:[]});}catch(_){setErreur(fr?'Vérifiez l’échelle et un contour de 3 à 32 coins sans croisement.':'Check scale and a 3–32-corner outline without crossings.');}}
 return <div className={s.options}><label className={s.importer}><span>{fr?'Déposer un PDF ou une image du plan':'Upload a PDF or floor plan image'}</span><input type="file" accept="application/pdf,image/png,image/jpeg,image/webp,.pdf" disabled={disabled||attente} aria-label={fr?'Déposer un PDF ou une image du plan':'Upload a PDF or floor plan image'} onChange={e=>{ouvrir(e.target.files[0]);e.target.value='';}}/></label>
 {attente&&<p role="status">{fr?'Ouverture du plan…':'Opening plan…'}</p>}
 {image&&<>
 {pdf?.numPages>1&&<label className={s.champ}><span>{fr?'Page du plan':'Floor plan page'}</span><select disabled={attente} value={page} onChange={async e=>{setAttente(true);try{await rendre(pdf,Number(e.target.value),jeton.current);}catch(_){setErreur(fr?'Page illisible.':'Unreadable page.');}finally{setAttente(false);}}}>{Array.from({length:Math.min(pdf.numPages,60)},(_,i)=><option key={i} value={i+1}>{i+1}</option>)}</select></label>}
 <p>{phase==='echelle'?(fr?'1. Touchez les deux extrémités d’une longueur connue, puis saisissez sa mesure.':'1. Tap the ends of a known length and enter its measurement.'):(fr?'2. Touchez tous les coins de la pièce dans l’ordre. Ne répétez pas le premier.':'2. Tap every room corner in order. Do not repeat the first.')}</p>
 <svg viewBox={`0 0 ${taille.join(' ')}`} onPointerDown={poser} style={{width:'100%',maxWidth:`${62*taille[0]/taille[1]}svh`,height:'auto',margin:'0 auto',display:'block',touchAction:'manipulation',cursor:'crosshair',background:'#fff'}} role="img" aria-label={fr?'Plan à tracer : touchez les coins':'Plan tracing area: tap corners'}>
 <image href={image} width={taille[0]} height={taille[1]}/><polyline points={(phase==='echelle'?repere:points).map(p=>p.join(',')).join(' ')} stroke="#B84A23" fill="none" strokeWidth={taille[0]/240}/>{(phase==='echelle'?repere:points).map(([x,y],i)=><g key={i}><circle cx={x} cy={y} r={taille[0]/100} fill="#B84A23"/><text x={x+taille[0]/70} y={y-taille[0]/90} fontSize={taille[0]/35} fill="#111">{i+1}</text></g>)}
 </svg>
 {phase==='echelle'?<><label className={s.champ}><span>{fr?'Longueur réelle (m)':'Real length (m)'}</span><input inputMode="decimal" value={longueur} onChange={e=>setLongueur(e.target.value)} placeholder="3,50"/></label><button type="button" disabled={distance<10||!Number.isFinite(metres)||metres<=0||metres>30} onClick={()=>setPhase('contour')}>{fr?'Tracer la pièce':'Trace the room'}</button></>:<div className={s.actions}><button type="button" disabled={!points.length} onClick={()=>setPoints(v=>v.slice(0,-1))}>{fr?'Annuler le dernier coin':'Undo last corner'}</button><button type="button" onClick={()=>{setPhase('echelle');setPoints([]);}}>{fr?'Revoir l’échelle':'Check scale'}</button><button type="button" className={s.plein} disabled={points.length<3||disabled} onClick={utiliser}>{fr?'Vérifier ce contour':'Check this outline'}</button></div>}
 <p className={s.note}>{fr?'Tracez une seule pièce. Ajoutez ensuite les portes et fenêtres dans le plan éditable. Le document reste dans votre navigateur.':'Trace one room. Add openings in the editable plan afterwards. The document stays in your browser.'}</p></>}
 {erreur&&<p role="alert" className={s.erreur}>{erreur}</p>}</div>;
}
